Args = --features=enkan.graalvm.EnkanFeature,kotowari.graalvm.KotowariFeature \
       --initialize-at-build-time=enkan.util.MixinUtils,kotowari.graalvm.NativeDispatcherRegistry,kotowari.graalvm.KotowariDispatcher,org.jboss.logging.JDKLevel \
       -H:+ReportExceptionStackTraces
